FROM golang:1.3.3-cross
MAINTAINER peter.edge@gmail.com

RUN mkdir -p /go/src/github.com/peter-edge/go-dockerclient
ADD . /go/src/github.com/peter-edge/go-dockerclient/
WORKDIR /go/src/github.com/peter-edge/go-dockerclient
